spring.application.name=nenpi
# MySQL 데이터베이스 연결 설정
spring.datasource.url=jdbc:mysql://localhost:3307/my_nenpi?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=a1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA 설정
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect

#python path
python.script.path=src/main/java/com/kang/nenpi/python/tenki/tenkitest.py